export const FETCH_TEST_QUESTIONS = 'FETCH_TEST_QUESTIONS';
export const SET_TEST_QUESTIONS = 'SET_TEST_QUESTIONS';

export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTION_SUCCSESS = 'ADD_QUESTION_SUCCSESS';

export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const REMOVE_QUESTION_SUCCSESS = 'REMOVE_QUESTION_SUCCSESS';

export const EDITING_QUESTION = 'EDITING_QUESTION';
export const EDIT_QUESTON_SERV = 'EDIT_QUESTON_SERV';
export const SAVE_EDITED_QUESTION = 'SAVE_EDITED_QUESTION';
