export const OPEN_MODAL_TO_LOGIN = "OPEN_MODAL_TO_LOGIN";
export const OPEN_MODAL_TO_ADD_TEST = "OPEN_MODAL_TO_ADD_TEST";
export const OPEN_MODAL_TO_ADD_QUESTION = "OPEN_MODAL_TO_ADD_QUESTION";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const OPEN_CONFIRMATION = 'OPEN_CONFIRMATION';
