export const FETCH_TESTS = 'FETCH_TESTS';
export const SET_TESTS = 'SET_TESTS';

export const ADD_TEST = "ADD_TEST";
export const ADD_TEST_SUCCSESS = 'ADD_TEST_SUCCSESS';

export const REMOVE_TEST = 'REMOVE_TEST';
export const REMOVE_TEST_SUCCSESS = "REMOVE_TEST_SUCCSESS";

export const EDIT_TEST_NAME = "EDIT_TEST_NAME";
export const SAVE_TEST_NAME = "SAVE_TEST_NAME";
export const SAVE_TEST_NAME_SUCCSESS ='SAVE_TEST_NAME_SUCCSESS';